werkzeug - INFO -  * Running on http://192.168.200.227:5000/ (Press CTRL+C to quit)
root - WARNING - Updating stock
root - WARNING - Starting to load orders 
root - WARNING - Starting to load products
root - ERROR - Error al importar la grupo de tallas con Id '10' y Nombre 'ï¿½nica'.
Error: Violation of UNIQUE KEY constraint 'UQ__SizeGrou__09E411E35A48F4A3'. Cannot insert duplicate key in object 'dbo.SizeGroup'. The duplicate key value is (<NULL>, ï¿½nica).
The statement has been terminated.
root - WARNING - New Size Group created
root - ERROR - Transaction not connected, or was disconnected
root - WARNING - New Productcreated
root - WARNING - Updating stock
root - ERROR - The product does not exist
main - ERROR - Exception on /api/loadOrders [GET]
Traceback (most recent call last):
  File "C:\Users\Christian\Documents\shopifyAgora\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Christian\Documents\shopifyAgora\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Christian\Documents\shopifyAgora\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Christian\Documents\shopifyAgora\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Christian\Documents\shopifyAgora\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Christian\Documents\shopifyAgora\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Christian\Documents\shopifyAgora\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/Christian/Documents/shopifyAgora/main.py", line 555, in loadOrders
    cursor.execute(
pyodbc.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near ';'. (102) (SQLExecDirectW)")
werkzeug - INFO - 192.168.200.227 - - [11/Sep/2020 17:08:02] "[35m[1mGET /api/loadOrders HTTP/1.1[0m" 500 -
root - WARNING - Updating stock
root - WARNING - Starting to load orders 
root - WARNING - Starting to load products
root - ERROR - Error al importar la grupo de tallas con Id '10' y Nombre 'ï¿½nica'.
Error: Violation of UNIQUE KEY constraint 'UQ__SizeGrou__09E411E35A48F4A3'. Cannot insert duplicate key in object 'dbo.SizeGroup'. The duplicate key value is (<NULL>, ï¿½nica).
The statement has been terminated.
root - WARNING - New Size Group created
root - ERROR - Transaction not connected, or was disconnected
root - WARNING - New Productcreated
root - WARNING - Updating stock
root - ERROR - The product does not exist
main - ERROR - Exception on /api/loadOrders [GET]
Traceback (most recent call last):
  File "C:\Users\Christian\Documents\shopifyAgora\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Christian\Documents\shopifyAgora\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Christian\Documents\shopifyAgora\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Christian\Documents\shopifyAgora\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Christian\Documents\shopifyAgora\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Christian\Documents\shopifyAgora\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Christian\Documents\shopifyAgora\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/Christian/Documents/shopifyAgora/main.py", line 555, in loadOrders
    cursor.execute(
pyodbc.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near ';'. (102) (SQLExecDirectW)")
werkzeug - INFO - 192.168.200.227 - - [11/Sep/2020 17:08:24] "[35m[1mGET /api/loadOrders HTTP/1.1[0m" 500 -
root - WARNING - Updating stock
root - WARNING - Starting to load orders 
root - WARNING - Starting to load products
root - ERROR - 
root - WARNING - New Size Group created
root - ERROR - 
root - WARNING - New Family created
root - ERROR - 
root - WARNING - New Productcreated
root - ERROR - 
root - WARNING - New Size Group created
root - ERROR - 
root - WARNING - New Color Group created
root - ERROR - 
root - WARNING - New Family created
root - ERROR - 
root - WARNING - New Productcreated
root - ERROR - 
root - WARNING - New Size Group created
root - ERROR - 
root - WARNING - New Color Group created
root - ERROR - 
root - WARNING - New Family created
root - ERROR - 
root - WARNING - New Productcreated
root - ERROR - 
root - WARNING - New Size Group created
root - ERROR - 
root - WARNING - New Color Group created
root - ERROR - 
root - WARNING - New Productcreated
root - ERROR - 
root - WARNING - New Family created
root - ERROR - 
root - WARNING - New Productcreated
root - ERROR - 
root - WARNING - New Size Group created
root - ERROR - 
root - WARNING - New Color Group created
root - ERROR - 
root - WARNING - New Productcreated
root - ERROR - Error al importar la grupo de tallas con Id '10' y Nombre 'ï¿½nica'.
Error: Violation of UNIQUE KEY constraint 'UQ__SizeGrou__09E411E3CCF23AB8'. Cannot insert duplicate key in object 'dbo.SizeGroup'. The duplicate key value is (<NULL>, ï¿½nica).
The statement has been terminated.
root - WARNING - New Size Group created
root - ERROR - 
root - WARNING - New Family created
root - ERROR - 
root - WARNING - New Productcreated
root - WARNING - Updating stock
root - ERROR - 
root - WARNING - New customer created
root - ERROR - 
root - WARNING - New order created
root - ERROR - 
root - WARNING - New order created
root - ERROR - 
root - WARNING - New order created
root - ERROR - 
root - WARNING - New order created
root - ERROR - 
root - WARNING - New order created
root - ERROR - 
root - WARNING - New order created
root - ERROR - 
root - WARNING - New order created
root - ERROR - 
root - WARNING - New order created
root - ERROR - 
root - WARNING - New order created
werkzeug - INFO - 192.168.200.227 - - [11/Sep/2020 17:10:23] "[37mGET /api/loadOrders HTTP/1.1[0m" 200 -
root - WARNING - Updating stock
root - WARNING - Starting to load orders 
root - WARNING - Starting to load products
root - ERROR - 
root - WARNING - New Size Group created
root - ERROR - 
root - WARNING - New Color Group created
root - ERROR - 
root - WARNING - New Family created
root - ERROR - 
root - WARNING - New Productcreated
root - WARNING - Updating stock
root - ERROR - 
root - WARNING - New order created
root - ERROR - 
root - WARNING - New order created
werkzeug - INFO - 192.168.200.227 - - [11/Sep/2020 17:32:24] "[37mGET /api/loadOrders HTTP/1.1[0m" 200 -
root - WARNING - Updating stock
root - WARNING - Starting to load orders 
root - WARNING - Starting to load products
root - WARNING - Updating stock
werkzeug - INFO - 192.168.200.227 - - [11/Sep/2020 17:37:53] "[37mGET /api/loadOrders HTTP/1.1[0m" 200 -
